// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.6.1
// source: packages/proto/wallet.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "wallet";

export interface CreateWalletDto {
  userId: string;
}

export interface GetWalletDto {
  id: string;
}

export interface CreditWalletDto {
  walletId: string;
  userId: string;
  amount: string;
}

export interface DebitWalletDto {
  walletId: string;
  userId: string;
  amount: string;
}

export interface WalletResponse {
  status: string;
  message: string;
  data: Wallet | undefined;
}

export interface Wallet {
  id: string;
  userId: string;
  balance: string;
}

export const WALLET_PACKAGE_NAME = "wallet";

export interface WalletServiceClient {
  createWallet(request: CreateWalletDto): Observable<WalletResponse>;

  getWallet(request: GetWalletDto): Observable<WalletResponse>;

  creditWallet(request: CreditWalletDto): Observable<WalletResponse>;

  debitWallet(request: DebitWalletDto): Observable<WalletResponse>;
}

export interface WalletServiceController {
  createWallet(request: CreateWalletDto): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;

  getWallet(request: GetWalletDto): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;

  creditWallet(request: CreditWalletDto): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;

  debitWallet(request: DebitWalletDto): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;
}

export function WalletServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createWallet", "getWallet", "creditWallet", "debitWallet"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("WalletService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("WalletService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const WALLET_SERVICE_NAME = "WalletService";
