// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.6.1
// source: packages/proto/user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface CreateUserDto {
  email: string;
  name: string;
}

export interface GetUserByIdDto {
  id: string;
}

export interface User {
  id: string;
  email: string;
  name: string;
}

export interface CreateUserResponse {
  status: string;
  message: string;
  data: User | undefined;
}

export interface GetUserByIdResponse {
  status: string;
  message: string;
  data: User | undefined;
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  createUser(request: CreateUserDto): Observable<CreateUserResponse>;

  getUserById(request: GetUserByIdDto): Observable<GetUserByIdResponse>;
}

export interface UserServiceController {
  createUser(request: CreateUserDto): Promise<CreateUserResponse> | Observable<CreateUserResponse> | CreateUserResponse;

  getUserById(
    request: GetUserByIdDto,
  ): Promise<GetUserByIdResponse> | Observable<GetUserByIdResponse> | GetUserByIdResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createUser", "getUserById"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
